# Generated by Django 3.2.4 on 2021-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(default='', max_length=20)),
                ('proprice', models.IntegerField(default=0)),
                ('prodescription', models.CharField(default='', max_length=200)),
                ('date', models.DateField()),
                ('proimage', models.ImageField(default='', upload_to='productimg/')),
            ],
        ),
    ]
