# Generated by Django 3.2.4 on 2021-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
